[package]
name = "circus-frontend-exporter"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
adt-into = {path = "adt-into"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
itertools = "0.10.5"
clap = { version = "4.0", features = ["derive"] }
paste = "1.0.11"

[features]
default = ["minimal-ast"]
minimal-ast = []
