[package]
name = "circus-lint"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
circus-diagnostics = { version = "=0.1.0", path = "../diagnostics" }
log = "0.4"
