[package]
name = "circus-cli-options-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
itertools = "0.10.5"
clap.workspace = true
circus-diagnostics.workspace = true
circus-cli-options.workspace = true
circus-frontend-exporter.workspace = true
circus-frontend-exporter-options.workspace = true
path-clean = "1.0.1"

